<a href="https://colab.research.google.com/github/gnanimail/NLP/blob/master/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
data=pd.DataFrame({"text":["GenerativeAI uses LLM","LLM uses LLM","people write prompt","LLM genereate response"],"output":[1,1,0,0]})

In [4]:
data.head()

text  output
0   GenerativeAI uses LLM       1
1            LLM uses LLM       1
2     people write prompt       0
3  LLM genereate response       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
BOW=CountVectorizer()

In [11]:
document_matrix=BOW.fit_transform(data["text"])

In [12]:
document_matrix

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [13]:
BOW.vocabulary_

{'generativeai': 0,
 'uses': 6,
 'llm': 2,
 'people': 3,
 'write': 7,
 'prompt': 4,
 'genereate': 1,
 'response': 5}

In [14]:
document_matrix[0].toarray()

array([[1, 0, 1, 0, 0, 0, 1, 0]])

In [15]:
document_matrix[1].toarray()

array([[0, 0, 2, 0, 0, 0, 1, 0]])

In [16]:
document_matrix[2].toarray()

array([[0, 0, 0, 1, 1, 0, 0, 1]])

In [17]:
document_matrix[3].toarray()

array([[0, 1, 1, 0, 0, 1, 0, 0]])

In [18]:
bigram=CountVectorizer(ngram_range=(2,2))

In [19]:
bigramvocab=bigram.fit_transform(data["text"])

In [20]:
bigram.vocabulary_

{'generativeai uses': 0,
 'uses llm': 5,
 'llm uses': 3,
 'people write': 4,
 'write prompt': 6,
 'llm genereate': 2,
 'genereate response': 1}

In [21]:
trigram=CountVectorizer(ngram_range=(3,3))

In [22]:
trigramdata=trigram.fit_transform(data["text"])

In [23]:
trigram.vocabulary_

{'generativeai uses llm': 0,
 'llm uses llm': 2,
 'people write prompt': 3,
 'llm genereate response': 1}

In [24]:
mix=CountVectorizer(ngram_range=(1,2))

In [25]:
mix_vocab=mix.fit_transform(data["text"])

In [27]:
mix.vocabulary_

{'generativeai': 0,
 'uses': 11,
 'llm': 4,
 'generativeai uses': 1,
 'uses llm': 12,
 'llm uses': 6,
 'people': 7,
 'write': 13,
 'prompt': 9,
 'people write': 8,
 'write prompt': 14,
 'genereate': 2,
 'response': 10,
 'llm genereate': 5,
 'genereate response': 3}

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
tfidf=TfidfVectorizer()

In [30]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.70203482, 0.        , 0.44809973, 0.        , 0.        ,
        0.        , 0.55349232, 0.        ],
       [0.        , 0.        , 0.8508161 , 0.        , 0.        ,
        0.        , 0.52546357, 0.        ],
       [0.        , 0.        , 0.        , 0.57735027, 0.57735027,
        0.        , 0.        , 0.57735027],
       [0.        , 0.64450299, 0.41137791, 0.        , 0.        ,
        0.64450299, 0.        , 0.        ]])

In [31]:
tfidf.get_feature_names_out()

array(['generativeai', 'genereate', 'llm', 'people', 'prompt', 'response',
       'uses', 'write'], dtype=object)

In [32]:
tfidf.idf_

array([1.91629073, 1.91629073, 1.22314355, 1.91629073, 1.91629073,
       1.91629073, 1.51082562, 1.91629073])